### ISSUE TITLE
feat: (diagram) Compare EVM transaction anatomy and Starknet transaction anatomy in an excalidraw diagram. 

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot-rpc#10]

**Comment by Flydexo** [comment]
We should think how to make the tx hash. Is it the starknet transaction hash or the hash used by the EVM user to sign. For the moment I have this

![Kakarot RPC relayer layer](https://user-images.githubusercontent.com/66029824/209710230-4b88327a-6157-4217-9591-525c5457986c.png)

**Comment by Eikix** [comment]
I think the tx hash should be what the user signed. Kakarot RPC should be responsible to establish a bijection between EVM tx hash (signed) and derived Starknet tx hash (for block explorer and traceability of txs)

What do you think?


Next question is how to establish a link?
Once one has a EVM tx hash, is the starknet tx hash deterministic?

**Comment by Flydexo** [comment]
If the nonce on EVM = nonce on starknet we can definitely do it: https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/transactions/#calculating_the_hash_of_a_v1_invoke_transaction
