### ISSUE TITLE
bug: handle Starknet signatures conversion to `r, s, v` parameters in Ethereum

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot-rpc#109]
# Bug Report

Currently, we convert the signature array from starknet transactions to r, s, v parameters that are used in ECDSA.
Currently, signatures has only two items, example of a starknet tx:

```json
{
        "calldata": [
          "0x1",
          "0x4a3621276a83251b557a8140e915599ae8e7b6207b067ea701635c0d509801e",
          "0x2d4c8ea4c8fb9f571d1f6f9b7692fff8e5ceaf73b1df98e7da8c1109b39ae9a",
          "0x0",
          "0x2",
          "0x2",
          "0x4767b873669406d25dddbf67356e385a14480979e5358a411955d692576aa30",
          "0x1"
        ],
        "max_fee": "0x11b1d9007c05c",
        "nonce": "0x18",
        "sender_address": "0xd90fd6aa27edd344c5cbe1fe999611416b268658e866a54265aaf50d9cf28d",
        "signature": [
          "0x3cd4f193f84704ce73cfb45abcdb0a169067b56821b267b9af6eb52531c94dc",
          "0x6e0fac18be9cddae718054b6fe1cf7448015c1ef5a4fa5a7919665e0126e585"
        ],
        "transaction_hash": "0x65eee3bd22766c75d5e5f55c747db41d192d0274a5579d8808b2c5850dd0f6a",
        "type": "INVOKE",
        "version": "0x1"
      },
```

**Current behavior:**

The bug manifests as, when transforming to Ethereum transactions, we do:

```rust
// Extracting the signature
ether_tx.r = felt_option_to_u256(v1.signature.get(0))?;
ether_tx.s = felt_option_to_u256(v1.signature.get(1))?;
ether_tx.v = felt_option_to_u256(v1.signature.get(2))?;
```

**Expected behavior:**

insert short code snippets here
```

We should find a way to properly map `r, s, v` args in our transaction reports

**Comment by greged93** [comment]
Hey @Eikix can I have this one?

**Comment by greged93** [comment]
Update: made a [PR](https://github.com/xJonathanLEI/starknet-rs/pull/315) on starknet-rs in order to add the `ec recover` functionality, the above bug should be easily fixed from here on.

**Comment by Eikix** [comment]
Very cool!

Looking at the Kakarot-RPC repo again, made me realise, there is an additional problem:

Essentially when a user signs an EVM transaction, the signature is embedded in the RLP payload inside the eth_sendRawTransaction call. 

Then, the Cairo EOA account is able to decode the RLP and grab the signature from there. This means that the "signature" field is left empty in the Starknet add_transaction call. In particular, it means the EOA account abstraction implementation for Kakarot never uses get_tx_info().signature field.
We had to do this to ensure EVM tx and signature are not tampered with.

Essentially, when a user calls get_tx on a Starknet node for a KKT tx, the "signature" field will be empty. This is because we never populate it in the first place when sending transactions.

We have two options:
1. When sending a KKT transaction to be submitted on Starknet, we grab the tx from the RLP tx payload, and add it (duplicated) inside the Signature field of a Starknet transaction.
2. When getting a Kakarot transaction, we can decode and "transform" the tx calldata and grab the signature from there.
i.e. make sure we only have the RLP encoded tx and drop the other params in the calldata array

**Comment by xJonathanLEI** [comment]
@Eikix New to Kakarot but what's wrong with `signature` field being empty?

**Comment by Eikix** [comment]
In my opinion, there is "nothing" wrong with the signature field being empty in terms of business logic, our custom Account (EOA) knows to look for the signature inside the RLP tx payload (inside the starknet tx calldata).

But I see that for getting blocks / txs (block explorers, tx receipt, etc), it appears we're getting Starknet transactions and trying to look into the signature field. 
The signature field is by design left empty by the RPC node when sending KKT txs to Starknet

**Comment by xJonathanLEI** [comment]
My 2 cents is that making "cosmetic" changes to the transaction structure at a cost to please off-chain applications is probably not worth it. If anything block explorers like StarkScan should support decoding Kakarot transactions properly (i.e., extracting signature from `calldata`) when they recognize it's a Kakarot tx.

**Comment by greged93** [comment]
Agree, would also populate the transaction correctly (option 1 @Eikix ) in order to avoid any compatibility issues. I can work on this if needed.

**Comment by xJonathanLEI** [comment]
I actually meant option 2 lol. Option 1 is duplicating tx data unnecessarily.

Option 2 is good because it also offloads signature extraction to an offchain layer (RPC), making it cheaper compared to forcing the account to do it on-chain.

**Comment by greged93** [comment]
Wouldn't implementing Option 1 offload from the EOA as he could just access it with `get_tx_info().signature` and at the same time avoid the extra load for block explorers who would need to check if the transaction is from Kakarot which encodes the signature in some way in `calldata` or from XXX which encodes the signature in another way?

**Comment by Eikix** [comment]
Currently what is happening is:
- User sends raw tx as per https://eips.ethereum.org/EIPS/eip-2718 
- RPC just passes it along and wraps it inside a Starknet transaction (adds a max_fee field, sender_address, and nonce and puts RLP payload inside calldata: https://github.com/sayajin-labs/kakarot-rpc/blob/b0c0c5eb90e81524c06313efcc8b6c3ba4f725c7/rpc/src/eth_rpc.rs#L596
- EOA decodes RLP, takes out signature, then hashes the tx fields to obtain tx hash and checks that tx signature is valid given user's EVM address and tx hash


We could instead:
- User sends raw tx
- RPC decodes tx, puts the signature inside the starknet `signature` tx field
- RPC RLP encodes tx fields inside starknet calldata field (except for signature?)
- EOA decodes payload, gets tx hash and checks signature is valid 
- EOA calls Kakarot (IAccount.execute) with tx fields

This simply puts most of the work on the RPC, whereas the "EVM" business logic is supposed to be inside Kakarot and the EOA. That being said, this would save a lot of gas. 



Option 1 meant that we don't change how the EOA behaves (for now) and we simply duplicate data inside the starknet `signature` tx field

**Comment by greged93** [comment]
ok got it, thanks for the explanation !

**Comment by Eikix** [comment]
We could present those 2 (or 3) options in next week's community call.

Roughly, we need to agree on whether the EOA should perform the logic (maybe more "decentralized", as anyone can just submit their raw EVM tx without much logic), or RPC (cheaper and ~faster).

In the meantime, I believe duplicating the signature in the `signature` field is ok-tier in the meantime (timeline ~week vs. ~month for refactor)
