### ISSUE TITLE
method: eth_blockNumber

### ISSUE THREAD

**Issue by jobez** [sayajin-labs/kakarot-rpc#11]
# eth_blockNumber
 ## Metadata
* name: eth_blockNumber
* prefix: eth
* state: ⚠️
* [specification](https://github.com/ethereum/execution-apis/blob/6709c2a795b707202e93c4f2867fa0bf2640a84f/src/eth/client.yaml#L32)

 
## Specification Description
Returns the number of most recent block.
 
### Parameters
 * None
 
### Returns
* uint64 - blockNumber
 
 ## Kakarot Logic
This method does not interact with the kakarot contract or any other starknet contract. 
 
### Starknet methods
Would be calling the corresponding `starknet_blockNumber` https://github.com/starkware-libs/starknet-specs/blob/master/starknet_vs_ethereum_node_apis.md

**Comment by Flydexo** [comment]
@Eikix does the blockhash needs to appear here ?

**Comment by Eikix** [comment]
I think not, since this only returns Kakarot's block number. This can be done outside of Kakarot -> 
receive call -> call Starknet's sequencer or Pathfinder to get current Starknet block number N -> return N
