### ISSUE TITLE
dev: run `cargo clippy --  -W clippy::pedantic -W clippy::nursery -W clippy::expect_used` and implement fixes

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot-rpc#112]
In order to improve the codebase's code quality, run:
`cargo clippy --  -W clippy::pedantic -W clippy::nursery -W clippy::expect_used` on the whole workspace and implement the advises it gives.

**Comment by dubzn** [comment]
Hi Elias, can i take this one?

**Comment by Eikix** [comment]
Sure!
