### ISSUE TITLE
refactor: as per cargo clippy --pedantic, shorten `transaction_receipt` and `starknet_block_to_eth_block` methods lengths

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot-rpc#123]
as pointed out in #121 

Some cargo clippy advisable changes are complex.

Two of them imply a refactor of `transaction_receipt` and `starknet_block_to_eth_block` methods to shorten their length.

![image](https://user-images.githubusercontent.com/66871571/221928561-0d8b350b-db62-4887-a742-6d296d6d258d.png)

![image](https://user-images.githubusercontent.com/66871571/221928575-282054c2-5b08-47ae-a39c-baadff21799d.png)

**Comment by dragan2234** [comment]
hey @Eikix can I get this one assigned?

**Comment by Eikix** [comment]
We're going to go through some amount of refactor, I'm closing this issue until we have a clear plan on how to refactor the core client module:)! 

Will update you as soon as I create the new issue so you can take the issue 🔥
