### ISSUE TITLE
Workshop: Rename "KAKAROT_CONTRACT_ACCOUNT_CLASS_HASH" to "ACCOUNT_CLASS_HASH"

### ISSUE THREAD

**Issue by danilowhk** [sayajin-labs/kakarot-rpc#124]
# Feature Request

We are looking into having "ubiquitous languages" in Kakarot so renaming "KAKAROT_CONTRACT_ACCOUNT_CLASS_HASH" to "ACCOUNT_CLASS_HASH" is something that is aligned with ubiquitous languages.

https://github.com/sayajin-labs/kakarot-rpc/blob/ab59ebfb3878b6606e293f7ce42150727cc973bb/core/src/client/constants.rs#L4

Change all the code parts that are necessary aswell

**Comment by dubzn** [comment]
Hi Danilo! can i take this one?

**Comment by danilowhk** [comment]
Assigned!

**Comment by Eikix** [comment]
Closing this optimistically as #125 closes this issue
