### ISSUE TITLE
bug: source `.env.example` fails 

### ISSUE THREAD

**Issue by bajpai244** [sayajin-labs/kakarot-rpc#133]
# Bug Report

**Kakarot RPC version:**

**HEAD** ->  [b4e148fc72c5a414199fe4bec3d0e3c3726d5fee](https://github.com/sayajin-labs/kakarot-rpc/commit/b4e148fc72c5a414199fe4bec3d0e3c3726d5fee)

**Current behavior:**

```shell
cp .env.example .env && source .env
```

The above will result in the following error:
```shell
source .env.example
.env.example:2: command not found: STARKNET_RPC_URL
.env.example:3: command not found: RUST_LOG
.env.example:4: command not found: KAKAROT_HTTP_RPC_ADDRESS
.env.example:5: command not found: KAKAROT_ADDRESS
.env.example:6: command not found: PROXY_ACCOUNT_CLASS_HASH
```

**Expected behavior:**

The `.env.example` should be in the correct format, so that when copied into `.env` and then used with `source`,  it should work fine.

**Steps to reproduce:**

```shell
cp .env.example .env && source .env
```

**Comment by dubzn** [comment]
Anyone working on this? I would be grateful to take it
