### ISSUE TITLE
feat: Update rpc-examples files to point to devnet 

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot-rpc#137]
# Feature Request
 Update rpc-examples routes to point to devnet's URL

**Comment by bajpai244** [comment]
@Eikix can you elaborate more on this? I cannot figure out where in the codebase these changes have to be implemented, thanks!

**Comment by Eikix** [comment]
Hey:)! My bad the issue was not so clear, 
I asked @greged93 to handle it
