### ISSUE TITLE
feat: replace kakarotup in all repo by unwrapped equivalent

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot-rpc#138]
As a general rule, we are in favor of minimal abstractions when possible (no magic as would others say).

Here, kakarotup does not add much value, it'd rather stick with the usual cargo commands for our use-case.

Let's remove all instances of `sh kakarotup` and mentions of it in the readme and replace them by the natural usage of runs: `cargo build`, `git pull` etc. 

1. Check what kakarotup does
2. Replace its mentions in readme
3. Replace its mentions in makefile
4. Check that the requirements for the repo are clear (rust, git, etc.)

**Comment by bajpai244** [comment]
@Eikix , I went through Kakrotup and it seems like overkill here, I guess the makefile added in #134 should be more than enough to handle the build!

We are already offering a docker image which should be more than enough who want an easy-to-deploy version of it! They can just run a container of this image!

So I guess we can simply do the following:
- remove kakarotup
- remove it from the docs
- go with `make build`

If you approve of this approach then feel free to assign this to me!

**Comment by Eikix** [comment]
Awesome! 
LFG 🔥

**Comment by bajpai244** [comment]
LFG 🔥
