### ISSUE TITLE
feat: Kakarot Rpc method "eth_call"

### ISSUE THREAD

**Issue by danilowhk** [sayajin-labs/kakarot-rpc#17]
# eth_call

## Metadata

- name: call
- prefix: eth
- state: ⚠️
- [specification](https://github.com/ethereum/execution-apis/blob/6709c2a795b707202e93c4f2867fa0bf2640a84f/src/eth/execute.yaml#L1)

## Specification Description

Describe the method

### Parameters

- transaction_data

### Returns

- return_data

## Kakarot Logic

Describe the interaction with Kakarot and/or Starknet.
e.g. "this method does not interact with the kakarot contract or any other starknet contract."

### Kakarot methods

Which Kakarot methods are called?

### Starknet methods

Which Starknet RPC methods are called? e.g. "Would be calling the corresponding `starknet_call` https://github.com/starkware-libs/starknet-specs/blob/master/starknet_vs_ethereum_node_apis.md"

**Comment by Eikix** [comment]
Call input has types: 

```rust
pub struct CallRequest {
    /// From
    pub from: Option<Address>,
    /// To
    pub to: Option<Address>,
    /// Gas Price
    pub gas_price: Option<U256>,
    /// EIP-1559 Max base fee the caller is willing to pay
    pub max_fee_per_gas: Option<U256>,
    /// EIP-1559 Priority fee the caller is paying to the block author
    pub max_priority_fee_per_gas: Option<U256>,
    /// Gas
    pub gas: Option<U256>,
    /// Value
    pub value: Option<U256>,
    /// Data
    pub data: Option<Bytes>,
    /// Nonce
    pub nonce: Option<U256>,
    /// AccessList
    pub access_list: Option<Vec<AccessListItem>>,
    /// EIP-2718 type
    #[serde(rename = "type")]
    pub transaction_type: Option<U256>,
}
```

and `Option<BlockId>`

We must take those input and figure out:
- The Starknet address of the EVM smart contract deployed through Kakarot.
- call Execute_at_address in view mode
- Return bytes

**Comment by Flydexo** [comment]
Is the view version of `execute_at_address` implemented ?
