### ISSUE TITLE
feat: Kakarot Rpc method "eth_getTransactionReceipt"

### ISSUE THREAD

**Issue by danilowhk** [sayajin-labs/kakarot-rpc#18]
# eth_getTransactionReceipt

## Metadata

- name: getTransactionReceipt
- prefix: eth
- state: ⚠️
- [specification](https://github.com/ethereum/execution-apis/blob/6709c2a795b707202e93c4f2867fa0bf2640a84f/src/eth/transaction.yaml#L42)

## Specification Description

Describe the method

### Parameters

- Address : address
- Block : BlockTag

### Returns

- BlockCount : uint

## Kakarot Logic

Describe the interaction with Kakarot and/or Starknet.
e.g. "this method does not interact with the kakarot contract or any other starknet contract."

### Kakarot methods

Which Kakarot methods are called?

### Starknet methods

Which Starknet RPC methods are called? e.g. "Would be calling the corresponding `starknet_getTransactionReceipt` https://github.com/starkware-libs/starknet-specs/blob/master/starknet_vs_ethereum_node_apis.md"

**Comment by Eikix** [comment]
Is someone on this issue?

**Comment by irisdv** [comment]
Yes
