### ISSUE TITLE
feat: Kakarot Rpc method "eth_getTransactionCount" #16

### ISSUE THREAD

**Issue by danilowhk** [sayajin-labs/kakarot-rpc#19]
# eth_getTransactionCount

## Metadata

- name: getTransactionCount
- prefix: eth
- state: ⚠️
- [specification](https://github.com/ethereum/execution-apis/blob/6709c2a795b707202e93c4f2867fa0bf2640a84f/src/eth/state.yaml#L35)

## Specification Description

Describe the method

### Parameters

- None

### Returns

- uint64 - e.g. blockNumber

## Kakarot Logic

Describe the interaction with Kakarot and/or Starknet.
e.g. "this method does not interact with the kakarot contract or any other starknet contract."

### Kakarot methods

Which Kakarot methods are called?

### Starknet methods

Which Starknet RPC methods are called? e.g. "Would be calling the corresponding `starknet_getTransactionCount` https://github.com/starkware-libs/starknet-specs/blob/master/starknet_vs_ethereum_node_apis.md"

**Comment by danilowhk** [comment]
Will be working in this one :)

**Comment by Eikix** [comment]
What is the status of this issue?
