### ISSUE TITLE
Choose the ChainID

### ISSUE THREAD

**Issue by Flydexo** [sayajin-labs/kakarot-rpc#2]
What chainID should we choose for the RPC ? I first though of 9001 because it's over 9000 but EVMOS already took it. 

So 9000 as a fallback but seems not satisfying

Propose your ideas

**Comment by Flydexo** [comment]
Maybe 9001 in base 9 ? which gives 13311

**Comment by Eikix** [comment]
Hey how about this:
https://github.com/sayajin-labs/kakarot/blob/75bbe6ad7901223cae77a0191aa15b396a102a84/src/kakarot/constants.cairo#L33

**Comment by Flydexo** [comment]
Nice, waiting for move feedback and I add it

**Comment by Eikix** [comment]
Let's keep it that way:)! lfg
