### ISSUE TITLE
feat: Kakarot Rpc method "eth_gasPrice"

### ISSUE THREAD

**Issue by danilowhk** [sayajin-labs/kakarot-rpc#25]
# eth_gasPrice

## Metadata

- name: gasPrice
- prefix: eth
- state: ⚠️
- [specification](https://github.com/ethereum/execution-apis/blob/6709c2a795b707202e93c4f2867fa0bf2640a84f/src/eth/fee_market.yaml#L1)

## Specification Description

Describe the method

### Parameters

- None

### Returns

- GasPrice : uint

## Kakarot Logic

Describe the interaction with Kakarot and/or Starknet.
e.g. "this method does not interact with the kakarot contract or any other starknet contract."

### Kakarot methods

Which Kakarot methods are called?

### Starknet methods

Which Starknet RPC methods are called? e.g. "Would be calling the corresponding `starknet_gasPrice` https://github.com/starkware-libs/starknet-specs/blob/master/starknet_vs_ethereum_node_apis.md"

**Comment by Flydexo** [comment]
What should we return here ? The starknet gas price ?
