### ISSUE TITLE
feat: Kakarot Rpc method "eth_getLogs"

### ISSUE THREAD

**Issue by danilowhk** [sayajin-labs/kakarot-rpc#26]
# eth_getLogs

## Metadata

- name: getLogs
- prefix: eth
- state: ⚠️
- [specification](https://github.com/ethereum/execution-apis/blob/02ed29457134d0cf990ca4ad83e8034ed416cb3f/src/eth/filter.yaml#L55)

## Specification Description

Describe the method

### Parameters

- None

### Returns

- uint64 - e.g. blockNumber

## Kakarot Logic

Describe the interaction with Kakarot and/or Starknet.
e.g. "this method does not interact with the kakarot contract or any other starknet contract."

### Kakarot methods

Which Kakarot methods are called?

### Starknet methods

Which Starknet RPC methods are called? e.g. "Would be calling the corresponding `starknet_getLogs` https://github.com/starkware-libs/starknet-specs/blob/master/starknet_vs_ethereum_node_apis.md"

**Comment by Eikix** [comment]
Check kakarot repo, in testing @ClementWalter has adapted starknet logs to be readable in evm format

**Comment by Eikix** [comment]
Currently, logs in transaction receipt might be malformed, there'll need to be some amount of exploration.
eth_getLogs can check how logs were done inside the codebase already.

**Comment by ClementWalter** [comment]
see this https://github.com/sayajin-labs/kakarot/blob/85a6fcaab5bcfc54b3cae46bba612a9ebbcbb484/tests/integration/helpers/wrap_kakarot.py#L65

there is a try/catch because there is no guarantee that the event is an EVM event and not a Starknet one.
