### ISSUE TITLE
feat: eth_estimateGas [Needs Strategy Update ⚠️]

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot-rpc#45]
# eth_estimateGas

## Metadata

- name: estimateGas
- prefix: eth
- state: ⚠️
- [specification](https://github.com/ethereum/execution-apis/)

## Specification Description

Call an RPC node to estimate tx related gas : https://ethereum.github.io/execution-apis/api-documentation/

### Parameters

- Transaction
- Block

### Returns

- Gas used

## Kakarot Logic

Describe the interaction with Kakarot and/or Starknet.

**Comment by phklive** [comment]
I would be glad to take on this one :)

**Comment by Eikix** [comment]
I suggest you follow the following structure:
- use starknet's "simulateTransaction" rpc endpoint to get a `actual_fee` estimation
- then, we'll have to find a formula to separate gasPrice (baseFee + priorityFee) vs. gas_used

Here is my suggestion, will submit it for debate in Kakarot
- priorityFee will "always" be zero.
- baseFee will be set to the standard EIP1559 baseFee
- gas_used will be set as actual_fee / baseFee

**Comment by Eikix** [comment]
You can base your issue off of #60

**Comment by phklive** [comment]
At one point could we have a talk about the gas used by kakarot so i grasp everything correctly. 
Thanks.

**Comment by Eikix** [comment]
This issue needs more strategy, I'll clear assignees on it.
When we have clarity over how to estimate fees in Starknet given an Ethereum transaction payload, I'll reassign someone

**Comment by greged93** [comment]
Currently looking at two possible solutions:
- the `simulate_transaction` endpoint from the `feeder_gateway`: need to figure out how to add a simulation flag which would allow to skip the account validation step.
- skipping validation: deploy an EOA with an empty `__validate__` function. This would allow us to use the `simulate_transaction` endpoint (even without the skip validation flag) on this specific EOA without providing the signature.

**Comment by Eikix** [comment]
I think those two solutions are interesting,
@ClementWalter what do you think?

For context (french):
- le serveur RPC reçoit un objet Transaction qui contient toute une tx evm (sauf la signature)
- Starknet expect que tu exécute la tx localement donc en fait, Kakarot RPC devrait envoyer une tx comme si on se plaçait dans le contexte de eth_sendRawTransaction.


ouais en gros ma situation rêvée c'est :
- recevoir un call eth_estimateGas, une transaction evm pas encodée du tout (as per le type rust)
- le transformer en une raw tx as per eip2712 je crois (type de la tx, probably eip1559 | RLP encoded tx)
- formatter la rawTx dans une request starknet as per eth_sendRawTx
- envoyer le call estimateFee de starknet qui simule la tx 
- voir si on peut passer un flag no validate dans ce call car sinon, ça fail

**Comment by ClementWalter** [comment]
I don't really like the idea of deploying a dummy account with no validate, it seems odd to me, it would mean having an account on starknet that anyone can use to send true kakarot tx.

Since the `eth_call/eth_estimateGas` is unsigned, what do you think about adding a `eth_call` method to kakarot? It would:
- allow an easy fix to the above mentioned problem
- would allow any starknet contract to easily make a call/tx to a kakarot contract
- would not add a spurious Starknet account contract

**Comment by greged93** [comment]
Endpoint `estimate_fee` can be provided with an additional flag in order to skip validation on testnet. Working example below:
```
function rpc_call() {
     printf "Request:\n${1}\nReply:\n"
     curl -s -X POST \
          -H 'Content-Type: application/json' \
          -d "${1}" \
          https://alpha4.starknet.io/feeder_gateway/estimate_fee?skipValidate=true
     printf "\n\n"
}

rpc_call ' { 
            "type": "INVOKE_FUNCTION",
            "version": "0x1",
            "contract_address": "0x034525ee9fe25ce7f1d896ba5968464a3e6337fa8afb26097a76e79ebee3e28c",
            "calldata": [ 
                            "1",
                            "3267429884791031784129188059026496191501564961518175231747906707757621165072",
                            "1329909728320632088402217562277154056711815095720684343816173432540100887380",
                            "0",
                            "3",
                            "3",
                            "1081716377456466437556112403657435217051623770760970750771051979090071572060",
                            "1000000000000000000000",
                            "0"
            ],
            "signature": [],
            "max_fee": "0x000000000000000000000000000000000000000000000000016345785d8a0000",
            "nonce":   "0x0000000000000000000000000000000000000000000000000000000000000000"
        }'
```
