### ISSUE TITLE
feat: kakarot_getTokenBalances

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot-rpc#46]
# kakarot_getTokenBalances

## Metadata

- name: getTokenBalances
- prefix: kakarot
- state: ⚠️
- [specification](https://github.com/alchemyplatform/alchemy-web3#web3alchemygettokenbalancesaddress-contractaddresses)

## Specification Description

Returns token balances for a specific address given a list of contracts. 

### Parameters

- `address`: The address for which token balances will be checked.
- `contractAddresses`: An array of contract addresses. 

### Returns

An object with the following fields:

- `address`: The address for which token balances were checked.
- `tokenBalances`: An array of token balance objects. Each object contains:
    - `contractAddress`: The address of the contract.
    - `tokenBalance`: The balance of the contract, as a string representing a base-10 number.
    - `error`: An error string. Either `error` or `tokenBalance` will be null.

## Kakarot Logic

Calls Kakarot execute_at_address with "call signature" once for each `contractAddresses` index -> calls `balanceOf(address owner)` with parameter `owner == address`.
Reconstructs the return format.

### Kakarot methods

Call `execute_at_address` n times,`n == contractAddresses.len()`

**Comment by irisdv** [comment]
Can work on this issue
