### ISSUE TITLE
feat: eth_accounts

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot-rpc#53]
# eth_accounts

## Metadata

- name: accounts
- prefix: eth
- state: ⚠️
- [specification](https://ethereum.github.io/execution-apis/api-documentation/)

## Specification Description

Returns a list of accounts owned by the client.

### Parameters

- None

### Returns

- uint64 - e.g. blockNumber

## Kakarot Logic

No Kakarot logic.

For now, returns an empty Vector.

**Comment by phklive** [comment]
Would be glad to take on this issue.
