### ISSUE TITLE
feat: write down Kakarot "logs" into the transaction_receipt.logs

### ISSUE THREAD

**Issue by irisdv** [sayajin-labs/kakarot-rpc#78]
# Feature Request

**Describe the Feature Request**

Convert starknet transaction receipt logs to be EVM-format 'friendly' so it can be used in transaction_receipt. 

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by Eikix** [comment]
## Describe the Feature Request

Currently, getTransactionReceipt allows for getting a specific starknet transaction receipt and converting it to the Ethereum format.
Unfortunately, logs are not yet included in this process.

## Describe Preferred Solution

Write util to convert starknetlogs to eth logs.

**Comment by Eikix** [comment]
I'll try and take this for now

**Comment by Eikix** [comment]
resources: https://docs.starknet.io/documentation/architecture_and_concepts/Events/starknet-events/
