### ISSUE TITLE
dev: add tests for `vec_felt_to_bytes` 

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot-rpc#84]
Add unit testing for the function `vec_felt_to_bytes` in the helpers.rs file

**Comment by dpinones** [comment]
Hello there, may I take this one?

**Comment by dpinones** [comment]
Hi! I have a question are the `[vec_felt_to_bytes](https://github.com/sayajin-labs/kakarot-rpc/blob/ab59ebfb3878b6606e293f7ce42150727cc973bb/core/src/helpers.rs#L210)` and `[bytes_to_felt_vec](https://github.com/sayajin-labs/kakarot-rpc/blob/ab59ebfb3878b6606e293f7ce42150727cc973bb/core/src/helpers.rs#L262)` methods inverse of each other?

`
pub fn vec_felt_to_bytes(felt_vec: Vec<FieldElement>) -> Bytes {
    let felt_vec_in_u8: Vec<u8> = felt_vec.into_iter().flat_map(|x| x.to_bytes_be()).collect();
    Bytes::from(felt_vec_in_u8)
}

pub fn bytes_to_felt_vec(bytes: Bytes) -> Vec<FieldElement> {
    bytes.to_vec().into_iter().map(FieldElement::from).collect()
}
`
