### ISSUE TITLE
dev: update eth_getBlockTransactionCountByHash & byNumber to use starknet_getBlockTransactionCount

### ISSUE THREAD

**Issue by irisdv** [sayajin-labs/kakarot-rpc#92]
Currently `eth_getBlockTransactionCountByHash` and `eth_getBlockTransactionCountByNumber` functions both fetch `starknet_getBlockWithTxHashes` endpoint and then count the number of transactions in the block. When block is pending, both endpoints do not return anything. 

Both functions should use `starknet_getBlockTransactionCount` which returns the number of transactions for accepted and pending blocks.

**Comment by dpinones** [comment]
Hello there, may I take this one?

**Comment by Eikix** [comment]
Great! Let's do it:)
