### ISSUE TITLE
dev: refactor async for loops and try_join_all into join_all 

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot-rpc#98]
Currently we have the need to loop over futures.

We should use the idiomatic `join_all` method on futures instead of for loops.

`try_join_all` is suboptimal for our use case as it returns a `Result<Vec<_>>` meaning that it requires all the calls to succeed.

`join_all` returns a `Vec<Result<_>>` which lets you handle every case in a singular way.

Task: replace all For loops on Async Futures by `futures::join_all` and handle properly error cases for each vector element.

**Comment by hurrikaanig** [comment]
Hey @Eikix, can I try this ? I'd like to work a bit on the RPC :nerd_face:

**Comment by Eikix** [comment]
LFG:)!
